// SPDX-License-Identifier: MIT
// Writes firmware/app/src/flight_tables.hpp: the pitch program and the gain schedule the flight computers carry, designed on the nominal ascent of the
// 6-DOF vehicle (sim/vehicle/design.hpp). The firmware never designs anything: it loads these numbers. Run with an output path, or with no argument to
// print to stdout; the unit test `the_committed_firmware_tables_are_the_ones_the_design_gives` fails if the committed file differs from what the design gives now.
#include <cstdio>
#include <cstdlib>
#include <fstream>
#include <iostream>
#include <string>

#include "design.hpp"

namespace {

// A float as a C++ literal that reads back exactly: the shortest text that parses to the same float, with a decimal point so that it is a floating literal.
std::string lit(float v) {
  for (int digits = 1; digits <= 9; ++digits) {
    std::array<char, 32> b{};
    (void)std::snprintf(b.data(), b.size(), "%.*g", digits, static_cast<double>(v));
    if (std::strtof(b.data(), nullptr) == v) {
      std::string t = b.data();
      if (t.find_first_of(".eE") == std::string::npos) {
        t += ".0";
      }
      return t + "F";
    }
  }
  return "0.0F";  // not reached: nine digits always read back
}

std::string render(const sim::FlightTables& t) {
  std::string o;
  o += "// SPDX-License-Identifier: MIT\n";
  o += "// GENERATED by tools/vehicle/gen_tables.cpp from the 6-DOF vehicle's nominal ascent (sim/vehicle/design.hpp). Do not edit.\n";
  o += "// Regenerate: build/host/tfc_gen_tables firmware/app/src/flight_tables.hpp\n";
  o += "#pragma once\n#include \"tfc/controller.hpp\"\n\nnamespace fc::tables {\n\n";
  o += "inline void load(tfc::GainSchedule& gains, tfc::Guidance& guidance) {\n";
  for (unsigned i = 0; i < t.guidance.size(1U); ++i) {
    const tfc::GuidancePoint p = t.guidance.point(1U, i);
    o += "  (void)guidance.add(1U, " + std::to_string(p.frame) + "U, " + lit(p.deg) + ");\n";
  }
  for (unsigned i = 0; i < t.gains.size(); ++i) {
    const tfc::ControllerGains g = t.gains.gains_at(i);
    o += "  (void)gains.add(" + std::to_string(t.gains.frame_at(i)) + "U, tfc::ControllerGains{" + lit(g.kp) + ", " + lit(g.kd) + ", " + lit(g.ki) +
         "});\n";
  }
  o += "}\n\n}  // namespace fc::tables\n";
  return o;
}

}  // namespace

int main(int argc, char** argv) {
  const std::string text = render(sim::flight_tables(sim::Params{}));
  if (argc < 2) {
    std::cout << text;
    return 0;
  }
  std::ofstream out(argv[1], std::ios::binary);
  out << text;
  out.close();
  if (!out) {
    std::cerr << "cannot write " << argv[1] << "\n";
    return 1;
  }
  return 0;
}
