# SPDX-License-Identifier: MIT
"""Python mirror of core/include/tfc/protocol.hpp and crc8.hpp.

The C++ header is the source of truth. Float arithmetic is rounded to float32 at the same
points as the C++ code so quantisation matches bit for bit; tests/test_protocol.py pins
golden frames generated by the C++ implementation, and the replay tool re-decodes recorded
traffic with the real C++ code.
"""
from __future__ import annotations

import math
import os
import struct
from dataclasses import dataclass, field

# ---- CAN IDs (protocol.hpp, namespace id) ----
ID_SYNC = 0x010
ID_GYRO_BASE = 0x100
ID_ACCEL_BASE = 0x110
ID_CMD_BASE = 0x200
ID_ACT_OUT = 0x300
ID_HEARTBEAT = 0x400
ID_SIM = 0x500
ID_GROUND = 0x510

NODE_NAMES = "ABC"


def f32(x: float) -> float:
    """Round a Python float to float32, like a C++ `float` operation result."""
    return struct.unpack("<f", struct.pack("<f", x))[0]


# Fixed-point scales (protocol.hpp)
GYRO_LSB_DPS = f32(0.125)
ACCEL_LSB_G = f32(1.0 / 2048)
CMD_LSB_DEG = f32(0.001)


def crc8(data: bytes) -> int:
    """CRC-8/SAE-J1850: poly 0x1D, init 0xFF, xorout 0xFF, no reflection."""
    crc = 0xFF
    for b in data:
        crc ^= b
        for _ in range(8):
            crc = ((crc << 1) ^ 0x1D) & 0xFF if crc & 0x80 else (crc << 1) & 0xFF
    return crc ^ 0xFF


@dataclass
class Frame:
    id: int
    data: bytes = field(default=b"\x00" * 8)

    def __post_init__(self) -> None:
        self.data = bytes(self.data)
        if not 0 <= self.id <= 0x7FF:
            raise ValueError(f"standard CAN id out of range: {self.id:#x}")
        if len(self.data) > 8:
            raise ValueError("classic CAN payload is at most 8 bytes")

    def hex(self) -> str:
        return self.data.hex()


def quantize(v: float, lsb: float) -> int:
    """Mirror of tfc::quantize: float32 divide, saturate, round half away from zero."""
    if math.isnan(v):
        return 0
    if math.isinf(v):
        return 32767 if v > 0 else -32768
    q = f32(f32(v) / lsb)
    if q >= 32767.0:
        return 32767
    if q <= -32768.0:
        return -32768
    return int(f32(q + 0.5) if q >= 0.0 else f32(q - 0.5))  # int() truncates toward zero


def _put16(buf: bytearray, off: int, x: int) -> None:
    buf[off : off + 2] = struct.pack("<h", x)


def _get16(data: bytes, off: int) -> int:
    return struct.unpack_from("<h", data, off)[0]


def seal(payload6: bytes, seq: int) -> bytes:
    """6 data bytes | seq | crc8(bytes 0..6) -> 8-byte payload."""
    body = bytes(payload6) + bytes([seq & 0xFF])
    return body + bytes([crc8(body)])


def check(frame: Frame) -> bool:
    return len(frame.data) == 8 and frame.data[7] == crc8(frame.data[:7])


def seq_is_next(last: int, seq: int) -> bool:
    return ((last + 1) & 0xFF) == (seq & 0xFF)


# ---- Packers ----
def pack_vec3(can_id: int, values: tuple[float, float, float], lsb: float, seq: int) -> Frame:
    buf = bytearray(6)
    for i, v in enumerate(values):
        _put16(buf, 2 * i, quantize(v, lsb))
    return Frame(can_id, seal(bytes(buf), seq))


def pack_gyro(node: int, dps: tuple[float, float, float], seq: int) -> Frame:
    return pack_vec3(ID_GYRO_BASE + node, dps, GYRO_LSB_DPS, seq)


def pack_accel(node: int, g: tuple[float, float, float], seq: int) -> Frame:
    return pack_vec3(ID_ACCEL_BASE + node, g, ACCEL_LSB_G, seq)


def pack_cmd(node: int, pitch_deg: float, yaw_deg: float, digest: int, seq: int) -> Frame:
    buf = bytearray(6)
    _put16(buf, 0, quantize(pitch_deg, CMD_LSB_DEG))
    _put16(buf, 2, quantize(yaw_deg, CMD_LSB_DEG))
    _put16(buf, 4, struct.unpack("<h", struct.pack("<H", digest & 0xFFFF))[0])
    return Frame(ID_CMD_BASE + node, seal(bytes(buf), seq))


GROUND_OPS = {"reintegrate": 1, "disable": 2, "clear-disabled": 3, "clear-safe": 4}
GROUND_OP_NAMES = {v: k for k, v in GROUND_OPS.items()}
ARM_FLAG = 0x80

BENCH_KEY = bytes(range(16))  # the PUBLIC bench key shared with core/ (auth.hpp), the firmware default and the tests


def ground_key() -> bytes:
    """The key used for ground commands: $TFC_GROUND_KEY (32 hex digits) or the public bench key."""
    text = os.environ.get("TFC_GROUND_KEY")
    if not text:
        return BENCH_KEY
    try:
        key = bytes.fromhex(text)
    except ValueError:
        key = b""
    if len(key) != 16:
        raise ValueError("TFC_GROUND_KEY must be exactly 32 hex digits (128 bits)")
    return key


_M64 = (1 << 64) - 1


def _rotl(x: int, b: int) -> int:
    return ((x << b) | (x >> (64 - b))) & _M64


def siphash24(key: bytes, data: bytes) -> int:
    """SipHash-2-4 (reference algorithm; checked against the published vectors and against core/auth.hpp)."""
    k0 = int.from_bytes(key[:8], "little")
    k1 = int.from_bytes(key[8:16], "little")
    v = [k0 ^ 0x736F6D6570736575, k1 ^ 0x646F72616E646F6D, k0 ^ 0x6C7967656E657261, k1 ^ 0x7465646279746573]

    def rnd() -> None:
        v[0] = (v[0] + v[1]) & _M64
        v[1] = _rotl(v[1], 13) ^ v[0]
        v[0] = _rotl(v[0], 32)
        v[2] = (v[2] + v[3]) & _M64
        v[3] = _rotl(v[3], 16) ^ v[2]
        v[0] = (v[0] + v[3]) & _M64
        v[3] = _rotl(v[3], 21) ^ v[0]
        v[2] = (v[2] + v[1]) & _M64
        v[1] = _rotl(v[1], 17) ^ v[2]
        v[2] = _rotl(v[2], 32)

    n = len(data)
    for i in range(0, n - n % 8, 8):
        m = int.from_bytes(data[i:i + 8], "little")
        v[3] ^= m
        rnd()
        rnd()
        v[0] ^= m
    last = (n << 56) | int.from_bytes(data[n - n % 8:], "little")
    v[3] ^= last
    rnd()
    rnd()
    v[0] ^= last
    v[2] ^= 0xFF
    for _ in range(4):
        rnd()
    return (v[0] ^ v[1] ^ v[2] ^ v[3]) & _M64


def ground_mac(key: bytes, op_byte: int, node: int, counter: int) -> int:
    """32-bit tag of a ground command: low 32 bits of SipHash-2-4 over (id hi, id lo, opcode byte, node, counter)."""
    msg = bytes([(ID_GROUND >> 8) & 0xFF, ID_GROUND & 0xFF, op_byte & 0xFF, node & 0xFF, counter & 0xFF])
    return siphash24(key, msg) & 0xFFFFFFFF


def pack_ground(op: int, node: int, counter: int, key: bytes | None = None, arm: bool = False, forged: bool = False) -> Frame:
    """Operator command: opcode(+arm flag) | node | 32-bit tag | counter | crc8 (see core protocol.hpp, ADR-019).
    `forged` flips a bit of the tag (a frame an attacker without the key, or a corrupted frame with a valid CRC, would send)."""
    op_byte = (op & 0x7F) | (ARM_FLAG if arm else 0)
    tag = ground_mac(key if key is not None else ground_key(), op_byte, node, counter)
    if forged:
        tag ^= 0x00010000
    return Frame(ID_GROUND, seal(bytes([op_byte, node & 0xFF]) + tag.to_bytes(4, "little"), counter))


def pack_sync(frame_no: int, seq: int) -> Frame:
    """SYNC: 32-bit frame number (little endian) | 2 reserved bytes | seq | crc8."""
    return Frame(ID_SYNC, seal(struct.pack("<I", frame_no & 0xFFFFFFFF) + b"\x00\x00", seq))


# ---- Unpackers (return None when the CRC or length is bad, like `ok == false`) ----
@dataclass
class Vec3Sample:
    values: tuple[float, float, float]
    seq: int


@dataclass
class CmdSample:
    pitch_deg: float
    yaw_deg: float
    digest: int
    seq: int


def unpack_vec3(frame: Frame, lsb: float) -> Vec3Sample | None:
    if not check(frame):
        return None
    vals = tuple(f32(_get16(frame.data, 2 * i) * lsb) for i in range(3))
    return Vec3Sample(vals, frame.data[6])  # type: ignore[arg-type]


@dataclass
class SyncSample:
    frame_no: int
    seq: int


def unpack_sync(frame: Frame) -> SyncSample | None:
    if frame.id != ID_SYNC or not check(frame):
        return None
    return SyncSample(struct.unpack_from("<I", frame.data, 0)[0], frame.data[6])


@dataclass
class GroundSample:
    op: int
    node: int
    counter: int
    arm: bool
    tag: int


def unpack_ground(frame: Frame) -> GroundSample | None:
    if frame.id != ID_GROUND or not check(frame):
        return None
    return GroundSample(frame.data[0] & 0x7F, frame.data[1], frame.data[6], bool(frame.data[0] & ARM_FLAG),
                        int.from_bytes(frame.data[2:6], "little"))


def unpack_cmd(frame: Frame) -> CmdSample | None:
    if not check(frame):
        return None
    return CmdSample(
        f32(_get16(frame.data, 0) * CMD_LSB_DEG),
        f32(_get16(frame.data, 2) * CMD_LSB_DEG),
        struct.unpack_from("<H", frame.data, 4)[0],
        frame.data[6],
    )


def describe(frame: Frame) -> str:
    """One-line human-readable decode of a bus frame (used by `listen` and `decode`)."""
    i = frame.id
    if i == ID_SYNC:
        sy = unpack_sync(frame)
        return f"SYNC  -  frame={sy.frame_no} seq={sy.seq}" if sy else f"SYNC  -  CRC-BAD  {frame.hex()}"
    for base, name, lsb, unit in (
        (ID_GYRO_BASE, "GYRO", GYRO_LSB_DPS, "dps"),
        (ID_ACCEL_BASE, "ACCEL", ACCEL_LSB_G, "g"),
    ):
        if base <= i <= base + 2:
            node = NODE_NAMES[i - base]
            s = unpack_vec3(frame, lsb)
            if s is None:
                return f"{name:<5} {node}  CRC-BAD  {frame.hex()}"
            x, y, z = s.values
            return f"{name:<5} {node}  seq={s.seq:<3} [{x:+9.3f} {y:+9.3f} {z:+9.3f}] {unit}"
    if ID_CMD_BASE <= i <= ID_CMD_BASE + 2:
        node = NODE_NAMES[i - ID_CMD_BASE]
        c = unpack_cmd(frame)
        if c is None:
            return f"CMD   {node}  CRC-BAD  {frame.hex()}"
        return (f"CMD   {node}  seq={c.seq:<3} pitch={c.pitch_deg:+8.3f} yaw={c.yaw_deg:+8.3f} deg "
                f"digest={c.digest:#06x}")
    if i == ID_GROUND:
        g = unpack_ground(frame)
        if g is None:
            return f"GROUND -  CRC-BAD  {frame.hex()}"
        name = GROUND_OP_NAMES.get(g.op, f"op{g.op}")
        who = NODE_NAMES[g.node] if g.node < 3 else f"node{g.node}"
        verified = "tag ok under the bench key" if g.tag == ground_mac(BENCH_KEY, g.op | (ARM_FLAG if g.arm else 0), g.node, g.counter) else "tag NOT valid under the bench key"
        return f"GROUND -  {'ARM ' if g.arm else ''}{name} {who} counter={g.counter} ({verified})"
    if i == ID_ACT_OUT:
        return f"ACT   -  {frame.hex()}"
    if ID_HEARTBEAT <= i <= ID_HEARTBEAT + 2:
        return f"HB    {NODE_NAMES[i - ID_HEARTBEAT]}  {frame.hex()}"
    if i >= ID_SIM:
        return f"SIM   -  {frame.hex()}"
    return f"??? out-of-schedule id={i:#05x}  {frame.hex()}"
