# SPDX-License-Identifier: MIT
"""Python mirror of core/include/tfc/protocol.hpp and crc8.hpp.

The C++ header is the source of truth. Float arithmetic is rounded to float32 at the same
points as the C++ code so quantisation matches bit for bit; tests/test_protocol.py pins
golden frames generated by the C++ implementation, and the replay tool re-decodes recorded
traffic with the real C++ code.
"""
from __future__ import annotations

import math
import os
import struct
from dataclasses import dataclass, field

# ---- CAN IDs (protocol.hpp, namespace id) ----
ID_SYNC = 0x010
ID_GYRO_BASE = 0x100
ID_ACCEL_BASE = 0x110
ID_CMD_BASE = 0x200
ID_ACT_OUT = 0x300
ID_HEARTBEAT = 0x400
ID_STATE = 0x410          # + node: strike counts and the last accepted command counter
ID_RESYNC = 0x420         # + 4 * node + chunk: a quarter of a node's estimator and controller state (docs/RESYNC.md)
RESYNC_CHUNKS = 4
ID_SIM = 0x500            # the simulator's range is 0x500 to 0x50F (ID_SIM_LAST)
ID_SIM_RATES = 0x501
ID_SIM_ACCEL = 0x502
ID_SIM_STATE = 0x503
ID_SIM_TELEMETRY = 0x504
ID_SIM_FLAGS = 0x505
ID_SIM_LAST = 0x50F
ID_GROUND = 0x510

PROTOCOL_VERSION = 2

NODE_NAMES = "ABC"


def f32(x: float) -> float:
    """Round a Python float to float32, like a C++ `float` operation result."""
    return struct.unpack("<f", struct.pack("<f", x))[0]


# Fixed-point scales (protocol.hpp)
GYRO_LSB_DPS = f32(0.125)
ACCEL_LSB_G = f32(1.0 / 2048)
CMD_LSB_DEG = f32(0.001)


def crc8(data: bytes) -> int:
    """CRC-8/SAE-J1850: poly 0x1D, init 0xFF, xorout 0xFF, no reflection."""
    crc = 0xFF
    for b in data:
        crc ^= b
        for _ in range(8):
            crc = ((crc << 1) ^ 0x1D) & 0xFF if crc & 0x80 else (crc << 1) & 0xFF
    return crc ^ 0xFF


@dataclass
class Frame:
    id: int
    data: bytes = field(default=b"\x00" * 8)

    def __post_init__(self) -> None:
        self.data = bytes(self.data)
        if not 0 <= self.id <= 0x7FF:
            raise ValueError(f"standard CAN id out of range: {self.id:#x}")
        if len(self.data) > 8:
            raise ValueError("classic CAN payload is at most 8 bytes")

    def hex(self) -> str:
        return self.data.hex()


def quantize(v: float, lsb: float) -> int:
    """Mirror of tfc::quantize: float32 divide, saturate, round half away from zero."""
    if math.isnan(v):
        return 0
    if math.isinf(v):
        return 32767 if v > 0 else -32768
    q = f32(f32(v) / lsb)
    if q >= 32767.0:
        return 32767
    if q <= -32768.0:
        return -32768
    return int(f32(q + 0.5) if q >= 0.0 else f32(q - 0.5))  # int() truncates toward zero


def _put16(buf: bytearray, off: int, x: int) -> None:
    buf[off : off + 2] = struct.pack("<h", x)


def _get16(data: bytes, off: int) -> int:
    return struct.unpack_from("<h", data, off)[0]


def seal(payload6: bytes, seq: int) -> bytes:
    """6 data bytes | seq | crc8(bytes 0..6) -> 8-byte payload."""
    body = bytes(payload6) + bytes([seq & 0xFF])
    return body + bytes([crc8(body)])


def check(frame: Frame) -> bool:
    return len(frame.data) == 8 and frame.data[7] == crc8(frame.data[:7])


def seq_is_next(last: int, seq: int) -> bool:
    return ((last + 1) & 0xFF) == (seq & 0xFF)


# ---- Packers ----
def pack_vec3(can_id: int, values: tuple[float, float, float], lsb: float, seq: int) -> Frame:
    buf = bytearray(6)
    for i, v in enumerate(values):
        _put16(buf, 2 * i, quantize(v, lsb))
    return Frame(can_id, seal(bytes(buf), seq))


def pack_gyro(node: int, dps: tuple[float, float, float], seq: int) -> Frame:
    return pack_vec3(ID_GYRO_BASE + node, dps, GYRO_LSB_DPS, seq)


def pack_accel(node: int, g: tuple[float, float, float], seq: int) -> Frame:
    return pack_vec3(ID_ACCEL_BASE + node, g, ACCEL_LSB_G, seq)


def pack_cmd(node: int, pitch_deg: float, yaw_deg: float, digest: int, seq: int) -> Frame:
    buf = bytearray(6)
    _put16(buf, 0, quantize(pitch_deg, CMD_LSB_DEG))
    _put16(buf, 2, quantize(yaw_deg, CMD_LSB_DEG))
    _put16(buf, 4, struct.unpack("<h", struct.pack("<H", digest & 0xFFFF))[0])
    return Frame(ID_CMD_BASE + node, seal(bytes(buf), seq))


GROUND_OPS = {"reintegrate": 1, "disable": 2, "clear-disabled": 3, "clear-safe": 4, "launch": 5, "scrub": 6, "phase": 7, "noop": 8, "warm": 9}
NODELESS_OPS = ("clear-safe", "launch", "scrub", "noop")  # the node field is ignored
PHASE_OPS = ("phase",)  # the node field is a phase number 0..7 (docs/MISSION_PHASES.md), not a computer
PHASE_NAMES = ("off", "power-up", "pre-launch", "ascent", "coast", "pre-burn", "burn", "safed")
GROUND_OP_NAMES = {v: k for k, v in GROUND_OPS.items()}
ARM_FLAG = 0x80

BENCH_KEY = bytes(range(16))  # the PUBLIC bench key shared with core/ (auth.hpp), the firmware default and the tests


def ground_key() -> bytes:
    """The key used for ground commands: $TFC_GROUND_KEY (32 hex digits) or the public bench key."""
    text = os.environ.get("TFC_GROUND_KEY")
    if not text:
        return BENCH_KEY
    try:
        key = bytes.fromhex(text)
    except ValueError:
        key = b""
    if len(key) != 16:
        raise ValueError("TFC_GROUND_KEY must be exactly 32 hex digits (128 bits)")
    return key


_M64 = (1 << 64) - 1


def _rotl(x: int, b: int) -> int:
    return ((x << b) | (x >> (64 - b))) & _M64


def siphash24(key: bytes, data: bytes) -> int:
    """SipHash-2-4 (reference algorithm; checked against the published vectors and against core/auth.hpp)."""
    k0 = int.from_bytes(key[:8], "little")
    k1 = int.from_bytes(key[8:16], "little")
    v = [k0 ^ 0x736F6D6570736575, k1 ^ 0x646F72616E646F6D, k0 ^ 0x6C7967656E657261, k1 ^ 0x7465646279746573]

    def rnd() -> None:
        v[0] = (v[0] + v[1]) & _M64
        v[1] = _rotl(v[1], 13) ^ v[0]
        v[0] = _rotl(v[0], 32)
        v[2] = (v[2] + v[3]) & _M64
        v[3] = _rotl(v[3], 16) ^ v[2]
        v[0] = (v[0] + v[3]) & _M64
        v[3] = _rotl(v[3], 21) ^ v[0]
        v[2] = (v[2] + v[1]) & _M64
        v[1] = _rotl(v[1], 17) ^ v[2]
        v[2] = _rotl(v[2], 32)

    n = len(data)
    for i in range(0, n - n % 8, 8):
        m = int.from_bytes(data[i:i + 8], "little")
        v[3] ^= m
        rnd()
        rnd()
        v[0] ^= m
    last = (n << 56) | int.from_bytes(data[n - n % 8:], "little")
    v[3] ^= last
    rnd()
    rnd()
    v[0] ^= last
    v[2] ^= 0xFF
    for _ in range(4):
        rnd()
    return (v[0] ^ v[1] ^ v[2] ^ v[3]) & _M64


def ground_mac(key: bytes, op_byte: int, node: int, counter: int) -> int:
    """32-bit tag of a ground command: low 32 bits of SipHash-2-4 over (id hi, id lo, opcode byte, node, counter)."""
    msg = bytes([(ID_GROUND >> 8) & 0xFF, ID_GROUND & 0xFF, op_byte & 0xFF, node & 0xFF, counter & 0xFF])
    return siphash24(key, msg) & 0xFFFFFFFF


def pack_ground(op: int, node: int, counter: int, key: bytes | None = None, arm: bool = False, forged: bool = False) -> Frame:
    """Operator command: opcode(+arm flag) | node | 32-bit tag | counter | crc8 (see core protocol.hpp, ADR-019).
    `forged` flips a bit of the tag (a frame an attacker without the key, or a corrupted frame with a valid CRC, would send)."""
    op_byte = (op & 0x7F) | (ARM_FLAG if arm else 0)
    tag = ground_mac(key if key is not None else ground_key(), op_byte, node, counter)
    if forged:
        tag ^= 0x00010000
    return Frame(ID_GROUND, seal(bytes([op_byte, node & 0xFF]) + tag.to_bytes(4, "little"), counter))


# Mission frame carried in SYNC (docs/LAUNCH_SEQUENCE.md): 0 not launched, 1..1000 the countdown, 1001 T-zero, then frames of flight; 65535 the largest.
MISSION_NOT_LAUNCHED = 0
MISSION_COUNTDOWN_FRAMES = 1000
MISSION_MAX = 0xFFFF


def mission_in_countdown(m: int) -> bool:
    return 0 < m <= MISSION_COUNTDOWN_FRAMES


def mission_in_flight(m: int) -> bool:
    return m > MISSION_COUNTDOWN_FRAMES


def mission_flight_frames(m: int) -> int:
    return m - MISSION_COUNTDOWN_FRAMES - 1 if m > MISSION_COUNTDOWN_FRAMES else 0


def mission_frames_to_zero(m: int) -> int:
    return MISSION_COUNTDOWN_FRAMES + 1 - m if mission_in_countdown(m) else 0


def pack_sync(frame_no: int, seq: int, mission: int = MISSION_NOT_LAUNCHED) -> Frame:
    """SYNC: 32-bit frame number (little endian) | 16-bit mission frame | seq | crc8."""
    return Frame(ID_SYNC, seal(struct.pack("<IH", frame_no & 0xFFFFFFFF, mission & 0xFFFF), seq))


# ---- Unpackers (return None when the CRC or length is bad, like `ok == false`) ----
@dataclass
class Vec3Sample:
    values: tuple[float, float, float]
    seq: int


@dataclass
class CmdSample:
    pitch_deg: float
    yaw_deg: float
    digest: int
    seq: int


def unpack_vec3(frame: Frame, lsb: float) -> Vec3Sample | None:
    if not check(frame):
        return None
    vals = tuple(f32(_get16(frame.data, 2 * i) * lsb) for i in range(3))
    return Vec3Sample(vals, frame.data[6])  # type: ignore[arg-type]


@dataclass
class SyncSample:
    frame_no: int
    seq: int
    mission: int = 0


def unpack_sync(frame: Frame) -> SyncSample | None:
    if frame.id != ID_SYNC or not check(frame):
        return None
    return SyncSample(struct.unpack_from("<I", frame.data, 0)[0], frame.data[6], struct.unpack_from("<H", frame.data, 4)[0])


@dataclass
class GroundSample:
    op: int
    node: int
    counter: int
    arm: bool
    tag: int


def unpack_ground(frame: Frame) -> GroundSample | None:
    if frame.id != ID_GROUND or not check(frame):
        return None
    return GroundSample(frame.data[0] & 0x7F, frame.data[1], frame.data[6], bool(frame.data[0] & ARM_FLAG),
                        int.from_bytes(frame.data[2:6], "little"))


def unpack_cmd(frame: Frame) -> CmdSample | None:
    if not check(frame):
        return None
    return CmdSample(
        f32(_get16(frame.data, 0) * CMD_LSB_DEG),
        f32(_get16(frame.data, 2) * CMD_LSB_DEG),
        struct.unpack_from("<H", frame.data, 4)[0],
        frame.data[6],
    )


# ======================================================================================================================================
# Protocol version 2 (docs/PROTOCOL.md): mirror of the second half of protocol.hpp. The golden bytes in tests/test_protocol.py are the same as the
# ones pinned in tests/test_protocol_v2.cpp.
# ======================================================================================================================================
def _quantize_u16(v: float, lsb: float) -> int:
    """Mirror of tfc::detail::quantize_u16: a non-negative quantity, float32 divide, round half up, saturate at 65535; NaN and negatives are 0."""
    if math.isnan(v):
        return 0
    q = f32(f32(v) / lsb) if not math.isinf(v) else (math.inf if v > 0 else -math.inf)
    if not q > 0.0:
        return 0
    if q >= 65535.0:
        return 65535
    return int(f32(q + 0.5))


STATE_NAMES = ("Standby", "Nominal", "Safe-hold", "Safe-ramp", "Safe-neutral")
CAUSE_NAMES = ("none", "lost-votes", "fc-request", "hardware-line", "reset")
VOTE_STATUS_NAMES = ("Triplex", "Duplex", "DuplexMiscompare", "Simplex", "NoMajority", "NoData")
SIM_FLAG_SAFED = 0x01
SIM_FLAG_PLATFORM_SATURATED = 0x02
SIM_FLAG_ENGINE_OUT = 0x04
SIM_FLAG_COMMAND_HELD = 0x08
SIM_FLAG_ABORTED = 0x10


@dataclass
class ActOut:
    pitch_deg: float = 0.0
    yaw_deg: float = 0.0
    state: int = 0
    held: bool = False
    vote_status: int = 0
    voted_nodes: int = 0
    excluded_nodes: int = 0
    cause: int = 0
    seq: int = 0


def pack_act_out(a: ActOut, seq: int) -> Frame:
    buf = bytearray(6)
    _put16(buf, 0, quantize(a.pitch_deg, CMD_LSB_DEG))
    _put16(buf, 2, quantize(a.yaw_deg, CMD_LSB_DEG))
    w = ((a.state & 7) | ((1 if a.held else 0) << 3) | ((a.vote_status & 7) << 4) | ((a.voted_nodes & 7) << 7)
         | ((a.excluded_nodes & 7) << 10) | ((a.cause & 7) << 13))
    buf[4:6] = struct.pack("<H", w)
    return Frame(ID_ACT_OUT, seal(bytes(buf), seq))


def unpack_act_out(frame: Frame) -> ActOut | None:
    if frame.id != ID_ACT_OUT or not check(frame):
        return None
    w = struct.unpack_from("<H", frame.data, 4)[0]
    return ActOut(f32(_get16(frame.data, 0) * CMD_LSB_DEG), f32(_get16(frame.data, 2) * CMD_LSB_DEG), w & 7, bool((w >> 3) & 1), (w >> 4) & 7,
                  (w >> 7) & 7, (w >> 10) & 7, (w >> 13) & 7, frame.data[6])


@dataclass
class Heartbeat:
    protocol_version: int = PROTOCOL_VERSION
    mode: int = 0
    safe_requested: bool = False
    bus_alarm: bool = False
    role: int = 0
    quarantined: bool = False
    node_state: tuple[int, int, int] = (0, 0, 0)
    reset_count: int = 0
    release_hash: int = 0
    seq: int = 0
    ready: bool = False  # ready for launch (byte 1, bit 7)


def pack_heartbeat(node: int, h: Heartbeat, seq: int) -> Frame:
    buf = bytearray(6)
    buf[0] = h.protocol_version & 0xFF
    buf[1] = ((h.mode & 3) | ((1 if h.safe_requested else 0) << 2) | ((1 if h.bus_alarm else 0) << 3) | ((h.role & 3) << 4)
              | ((1 if h.quarantined else 0) << 6) | ((1 if h.ready else 0) << 7))
    buf[2] = (h.node_state[0] & 3) | ((h.node_state[1] & 3) << 2) | ((h.node_state[2] & 3) << 4)
    buf[3] = h.reset_count & 0xFF
    buf[4:6] = struct.pack("<H", h.release_hash & 0xFFFF)
    return Frame(ID_HEARTBEAT + node, seal(bytes(buf), seq))


def unpack_heartbeat(frame: Frame) -> Heartbeat | None:
    if not ID_HEARTBEAT <= frame.id < ID_HEARTBEAT + 3 or not check(frame):
        return None
    d = frame.data
    return Heartbeat(d[0], d[1] & 3, bool((d[1] >> 2) & 1), bool((d[1] >> 3) & 1), (d[1] >> 4) & 3, bool((d[1] >> 6) & 1),
                     (d[2] & 3, (d[2] >> 2) & 3, (d[2] >> 4) & 3), d[3], struct.unpack_from("<H", d, 4)[0], d[6],
                     ready=bool((d[1] >> 7) & 1))


@dataclass
class StateShare:
    strikes: tuple[int, int, int] = (0, 0, 0)
    command_counter: int = 0
    seq: int = 0


def pack_state_share(node: int, s: StateShare, seq: int) -> Frame:
    buf = bytearray(6)
    buf[0] = (s.strikes[0] & 15) | ((s.strikes[1] & 15) << 4)
    buf[1] = s.strikes[2] & 15
    buf[2] = s.command_counter & 0xFF
    return Frame(ID_STATE + node, seal(bytes(buf), seq))


def unpack_state_share(frame: Frame) -> StateShare | None:
    if not ID_STATE <= frame.id < ID_STATE + 3 or not check(frame):
        return None
    d = frame.data
    return StateShare((d[0] & 15, (d[0] >> 4) & 15, d[1] & 15), d[2], d[6])


def pack_resync(node: int, chunk: int, words: tuple[int, int, int], seq: int) -> Frame:
    """One of the four frames that carry a node's shared state: three signed 16-bit words, little-endian, then seq and CRC."""
    buf = bytearray(6)
    for i, w in enumerate(words):
        _put16(buf, 2 * i, w)
    return Frame(ID_RESYNC + RESYNC_CHUNKS * node + chunk, seal(bytes(buf), seq))


def unpack_resync(frame: Frame) -> tuple[int, int, tuple[int, int, int], int] | None:
    """(node, chunk, words, seq), or None if the frame is not a good resync frame."""
    if not ID_RESYNC <= frame.id < ID_RESYNC + 3 * RESYNC_CHUNKS or not check(frame):
        return None
    k = frame.id - ID_RESYNC
    d = frame.data
    return k // RESYNC_CHUNKS, k % RESYNC_CHUNKS, (_get16(d, 0), _get16(d, 2), _get16(d, 4)), d[6]


def pack_sim_rates(dps: tuple[float, float, float], seq: int) -> Frame:
    return pack_vec3(ID_SIM_RATES, dps, GYRO_LSB_DPS, seq)


def pack_sim_accel(g: tuple[float, float, float], seq: int) -> Frame:
    return pack_vec3(ID_SIM_ACCEL, g, ACCEL_LSB_G, seq)


@dataclass
class SimState:
    altitude_m: float = 0.0
    speed_ms: float = 0.0
    mass_kg: float = 0.0
    seq: int = 0


def pack_sim_state(s: SimState, seq: int) -> Frame:
    buf = struct.pack("<HHH", _quantize_u16(s.altitude_m, 10.0), _quantize_u16(s.speed_ms, 1.0), _quantize_u16(s.mass_kg, 1.0))
    return Frame(ID_SIM_STATE, seal(buf, seq))


def unpack_sim_state(frame: Frame) -> SimState | None:
    if frame.id != ID_SIM_STATE or not check(frame):
        return None
    a, v, m = struct.unpack_from("<HHH", frame.data, 0)
    return SimState(float(a * 10), float(v), float(m), frame.data[6])


@dataclass
class SimTelemetry:
    dynamic_pressure_pa: float = 0.0
    pitch_error_deg: float = 0.0
    yaw_error_deg: float = 0.0
    seq: int = 0


def pack_sim_telemetry(t: SimTelemetry, seq: int) -> Frame:
    buf = bytearray(6)
    buf[0:2] = struct.pack("<H", _quantize_u16(t.dynamic_pressure_pa, 10.0))
    _put16(buf, 2, quantize(t.pitch_error_deg, CMD_LSB_DEG))
    _put16(buf, 4, quantize(t.yaw_error_deg, CMD_LSB_DEG))
    return Frame(ID_SIM_TELEMETRY, seal(bytes(buf), seq))


def unpack_sim_telemetry(frame: Frame) -> SimTelemetry | None:
    if frame.id != ID_SIM_TELEMETRY or not check(frame):
        return None
    q = struct.unpack_from("<H", frame.data, 0)[0]
    return SimTelemetry(float(q * 10), f32(_get16(frame.data, 2) * CMD_LSB_DEG), f32(_get16(frame.data, 4) * CMD_LSB_DEG), frame.data[6])


@dataclass
class SimFlags:
    flags: int = 0
    engines_on: int = 0
    time_frames: int = 0
    seq: int = 0


def pack_sim_flags(s: SimFlags, seq: int) -> Frame:
    buf = bytes([s.flags & 0xFF, s.engines_on & 0xFF]) + struct.pack("<I", s.time_frames & 0xFFFFFFFF)
    return Frame(ID_SIM_FLAGS, seal(buf, seq))


def unpack_sim_flags(frame: Frame) -> SimFlags | None:
    if frame.id != ID_SIM_FLAGS or not check(frame):
        return None
    return SimFlags(frame.data[0], frame.data[1], struct.unpack_from("<I", frame.data, 2)[0], frame.data[6])


def _describe_v2(frame: Frame) -> str | None:
    i = frame.id
    if i == ID_ACT_OUT:
        a = unpack_act_out(frame)
        if a is None:
            return f"ACT   -  CRC-BAD  {frame.hex()}"
        state = STATE_NAMES[a.state] if a.state < len(STATE_NAMES) else f"state{a.state}"
        status = VOTE_STATUS_NAMES[a.vote_status] if a.vote_status < len(VOTE_STATUS_NAMES) else f"status{a.vote_status}"
        cause = CAUSE_NAMES[a.cause] if a.cause < len(CAUSE_NAMES) else f"cause{a.cause}"
        return (f"ACT   -  seq={a.seq:<3} pitch={a.pitch_deg:+8.3f} yaw={a.yaw_deg:+8.3f} deg  {state}{' HELD' if a.held else ''}  vote={status} "
                f"nodes={a.voted_nodes:03b} excluded={a.excluded_nodes:03b} cause={cause}")
    if ID_HEARTBEAT <= i < ID_HEARTBEAT + 3:
        h = unpack_heartbeat(frame)
        node = NODE_NAMES[i - ID_HEARTBEAT]
        if h is None:
            return f"HB    {node}  CRC-BAD  {frame.hex()}"
        return (f"HB    {node}  seq={h.seq:<3} v{h.protocol_version} mode={h.mode} role={('hot', 'warm', 'cold', '?')[h.role]}"
                f"{' SAFE-REQUESTED' if h.safe_requested else ''}{' BUS-ALARM' if h.bus_alarm else ''}{' QUARANTINED' if h.quarantined else ''}{' READY' if h.ready else ''} "
                f"view={''.join('HLPD'[s] for s in h.node_state)} resets={h.reset_count} release={h.release_hash:#06x}")
    if ID_STATE <= i < ID_STATE + 3:
        s = unpack_state_share(frame)
        node = NODE_NAMES[i - ID_STATE]
        if s is None:
            return f"STATE {node}  CRC-BAD  {frame.hex()}"
        return f"STATE {node}  seq={s.seq:<3} strikes={s.strikes} command_counter={s.command_counter}"
    if i == ID_SIM_RATES or i == ID_SIM_ACCEL:
        lsb, unit, name = (GYRO_LSB_DPS, "dps", "SIMRT") if i == ID_SIM_RATES else (ACCEL_LSB_G, "g", "SIMAC")
        v = unpack_vec3(frame, lsb)
        if v is None:
            return f"{name} -  CRC-BAD  {frame.hex()}"
        x, y, z = v.values
        return f"{name} -  seq={v.seq:<3} [{x:+9.3f} {y:+9.3f} {z:+9.3f}] {unit}"
    if i == ID_SIM_STATE:
        s = unpack_sim_state(frame)
        return (f"SIMST -  seq={s.seq:<3} altitude={s.altitude_m:.0f} m speed={s.speed_ms:.0f} m/s mass={s.mass_kg:.0f} kg" if s
                else f"SIMST -  CRC-BAD  {frame.hex()}")
    if i == ID_SIM_TELEMETRY:
        t = unpack_sim_telemetry(frame)
        return (f"SIMTL -  seq={t.seq:<3} q={t.dynamic_pressure_pa:.0f} Pa error pitch={t.pitch_error_deg:+.3f} yaw={t.yaw_error_deg:+.3f} deg" if t
                else f"SIMTL -  CRC-BAD  {frame.hex()}")
    if i == ID_SIM_FLAGS:
        f = unpack_sim_flags(frame)
        if f is None:
            return f"SIMFL -  CRC-BAD  {frame.hex()}"
        names = [n for bit, n in ((SIM_FLAG_SAFED, "safed"), (SIM_FLAG_PLATFORM_SATURATED, "platform-saturated"), (SIM_FLAG_ENGINE_OUT, "engine-out"),
                                  (SIM_FLAG_COMMAND_HELD, "command-held"), (SIM_FLAG_ABORTED, "aborted")) if f.flags & bit]
        return f"SIMFL -  seq={f.seq:<3} t={f.time_frames * 0.01:.2f} s engines={f.engines_on} flags={','.join(names) or '-'}"
    return None


def describe(frame: Frame) -> str:
    """One-line human-readable decode of a bus frame (used by `listen` and `decode`)."""
    i = frame.id
    v2 = _describe_v2(frame)
    if v2 is not None:
        return v2
    if i == ID_SYNC:
        sy = unpack_sync(frame)
        return f"SYNC  -  frame={sy.frame_no} seq={sy.seq}" if sy else f"SYNC  -  CRC-BAD  {frame.hex()}"
    for base, name, lsb, unit in (
        (ID_GYRO_BASE, "GYRO", GYRO_LSB_DPS, "dps"),
        (ID_ACCEL_BASE, "ACCEL", ACCEL_LSB_G, "g"),
    ):
        if base <= i <= base + 2:
            node = NODE_NAMES[i - base]
            s = unpack_vec3(frame, lsb)
            if s is None:
                return f"{name:<5} {node}  CRC-BAD  {frame.hex()}"
            x, y, z = s.values
            return f"{name:<5} {node}  seq={s.seq:<3} [{x:+9.3f} {y:+9.3f} {z:+9.3f}] {unit}"
    if ID_CMD_BASE <= i <= ID_CMD_BASE + 2:
        node = NODE_NAMES[i - ID_CMD_BASE]
        c = unpack_cmd(frame)
        if c is None:
            return f"CMD   {node}  CRC-BAD  {frame.hex()}"
        return (f"CMD   {node}  seq={c.seq:<3} pitch={c.pitch_deg:+8.3f} yaw={c.yaw_deg:+8.3f} deg "
                f"digest={c.digest:#06x}")
    if i == ID_GROUND:
        g = unpack_ground(frame)
        if g is None:
            return f"GROUND -  CRC-BAD  {frame.hex()}"
        name = GROUND_OP_NAMES.get(g.op, f"op{g.op}")
        who = NODE_NAMES[g.node] if g.node < 3 else f"node{g.node}"
        verified = "tag ok under the bench key" if g.tag == ground_mac(BENCH_KEY, g.op | (ARM_FLAG if g.arm else 0), g.node, g.counter) else "tag NOT valid under the bench key"
        return f"GROUND -  {'ARM ' if g.arm else ''}{name} {who} counter={g.counter} ({verified})"
    if i == ID_ACT_OUT:
        return f"ACT   -  {frame.hex()}"
    if ID_HEARTBEAT <= i <= ID_HEARTBEAT + 2:
        return f"HB    {NODE_NAMES[i - ID_HEARTBEAT]}  {frame.hex()}"
    if i >= ID_SIM:
        return f"SIM   -  {frame.hex()}"
    return f"??? out-of-schedule id={i:#05x}  {frame.hex()}"
