# SPDX-License-Identifier: MIT
"""Python mirror of core/include/tfc/protocol.hpp and crc8.hpp.

The C++ header is the source of truth. Float arithmetic is rounded to float32 at the same
points as the C++ code so quantisation matches bit for bit; tests/test_protocol.py pins
golden frames generated by the C++ implementation, and the replay tool re-decodes recorded
traffic with the real C++ code.
"""
from __future__ import annotations

import math
import struct
from dataclasses import dataclass, field

# ---- CAN IDs (protocol.hpp, namespace id) ----
ID_SYNC = 0x010
ID_GYRO_BASE = 0x100
ID_ACCEL_BASE = 0x110
ID_CMD_BASE = 0x200
ID_ACT_OUT = 0x300
ID_HEARTBEAT = 0x400
ID_SIM = 0x500

NODE_NAMES = "ABC"


def f32(x: float) -> float:
    """Round a Python float to float32, like a C++ `float` operation result."""
    return struct.unpack("<f", struct.pack("<f", x))[0]


# Fixed-point scales (protocol.hpp)
GYRO_LSB_DPS = f32(0.125)
ACCEL_LSB_G = f32(1.0 / 2048)
CMD_LSB_DEG = f32(0.001)


def crc8(data: bytes) -> int:
    """CRC-8/SAE-J1850: poly 0x1D, init 0xFF, xorout 0xFF, no reflection."""
    crc = 0xFF
    for b in data:
        crc ^= b
        for _ in range(8):
            crc = ((crc << 1) ^ 0x1D) & 0xFF if crc & 0x80 else (crc << 1) & 0xFF
    return crc ^ 0xFF


@dataclass
class Frame:
    id: int
    data: bytes = field(default=b"\x00" * 8)

    def __post_init__(self) -> None:
        self.data = bytes(self.data)
        if not 0 <= self.id <= 0x7FF:
            raise ValueError(f"standard CAN id out of range: {self.id:#x}")
        if len(self.data) > 8:
            raise ValueError("classic CAN payload is at most 8 bytes")

    def hex(self) -> str:
        return self.data.hex()


def quantize(v: float, lsb: float) -> int:
    """Mirror of tfc::quantize: float32 divide, saturate, round half away from zero."""
    if math.isnan(v):
        return 0
    if math.isinf(v):
        return 32767 if v > 0 else -32768
    q = f32(f32(v) / lsb)
    if q >= 32767.0:
        return 32767
    if q <= -32768.0:
        return -32768
    return int(f32(q + 0.5) if q >= 0.0 else f32(q - 0.5))  # int() truncates toward zero


def _put16(buf: bytearray, off: int, x: int) -> None:
    buf[off : off + 2] = struct.pack("<h", x)


def _get16(data: bytes, off: int) -> int:
    return struct.unpack_from("<h", data, off)[0]


def seal(payload6: bytes, seq: int) -> bytes:
    """6 data bytes | seq | crc8(bytes 0..6) -> 8-byte payload."""
    body = bytes(payload6) + bytes([seq & 0xFF])
    return body + bytes([crc8(body)])


def check(frame: Frame) -> bool:
    return len(frame.data) == 8 and frame.data[7] == crc8(frame.data[:7])


def seq_is_next(last: int, seq: int) -> bool:
    return ((last + 1) & 0xFF) == (seq & 0xFF)


# ---- Packers ----
def pack_vec3(can_id: int, values: tuple[float, float, float], lsb: float, seq: int) -> Frame:
    buf = bytearray(6)
    for i, v in enumerate(values):
        _put16(buf, 2 * i, quantize(v, lsb))
    return Frame(can_id, seal(bytes(buf), seq))


def pack_gyro(node: int, dps: tuple[float, float, float], seq: int) -> Frame:
    return pack_vec3(ID_GYRO_BASE + node, dps, GYRO_LSB_DPS, seq)


def pack_accel(node: int, g: tuple[float, float, float], seq: int) -> Frame:
    return pack_vec3(ID_ACCEL_BASE + node, g, ACCEL_LSB_G, seq)


def pack_cmd(node: int, pitch_deg: float, yaw_deg: float, digest: int, seq: int) -> Frame:
    buf = bytearray(6)
    _put16(buf, 0, quantize(pitch_deg, CMD_LSB_DEG))
    _put16(buf, 2, quantize(yaw_deg, CMD_LSB_DEG))
    _put16(buf, 4, struct.unpack("<h", struct.pack("<H", digest & 0xFFFF))[0])
    return Frame(ID_CMD_BASE + node, seal(bytes(buf), seq))


def pack_sync(frame_no: int, seq: int) -> Frame:
    """SYNC: 32-bit frame number (little endian) | 2 reserved bytes | seq | crc8."""
    return Frame(ID_SYNC, seal(struct.pack("<I", frame_no & 0xFFFFFFFF) + b"\x00\x00", seq))


# ---- Unpackers (return None when the CRC or length is bad, like `ok == false`) ----
@dataclass
class Vec3Sample:
    values: tuple[float, float, float]
    seq: int


@dataclass
class CmdSample:
    pitch_deg: float
    yaw_deg: float
    digest: int
    seq: int


def unpack_vec3(frame: Frame, lsb: float) -> Vec3Sample | None:
    if not check(frame):
        return None
    vals = tuple(f32(_get16(frame.data, 2 * i) * lsb) for i in range(3))
    return Vec3Sample(vals, frame.data[6])  # type: ignore[arg-type]


@dataclass
class SyncSample:
    frame_no: int
    seq: int


def unpack_sync(frame: Frame) -> SyncSample | None:
    if frame.id != ID_SYNC or not check(frame):
        return None
    return SyncSample(struct.unpack_from("<I", frame.data, 0)[0], frame.data[6])


def unpack_cmd(frame: Frame) -> CmdSample | None:
    if not check(frame):
        return None
    return CmdSample(
        f32(_get16(frame.data, 0) * CMD_LSB_DEG),
        f32(_get16(frame.data, 2) * CMD_LSB_DEG),
        struct.unpack_from("<H", frame.data, 4)[0],
        frame.data[6],
    )


def describe(frame: Frame) -> str:
    """One-line human-readable decode of a bus frame (used by `listen` and `decode`)."""
    i = frame.id
    if i == ID_SYNC:
        sy = unpack_sync(frame)
        return f"SYNC  -  frame={sy.frame_no} seq={sy.seq}" if sy else f"SYNC  -  CRC-BAD  {frame.hex()}"
    for base, name, lsb, unit in (
        (ID_GYRO_BASE, "GYRO", GYRO_LSB_DPS, "dps"),
        (ID_ACCEL_BASE, "ACCEL", ACCEL_LSB_G, "g"),
    ):
        if base <= i <= base + 2:
            node = NODE_NAMES[i - base]
            s = unpack_vec3(frame, lsb)
            if s is None:
                return f"{name:<5} {node}  CRC-BAD  {frame.hex()}"
            x, y, z = s.values
            return f"{name:<5} {node}  seq={s.seq:<3} [{x:+9.3f} {y:+9.3f} {z:+9.3f}] {unit}"
    if ID_CMD_BASE <= i <= ID_CMD_BASE + 2:
        node = NODE_NAMES[i - ID_CMD_BASE]
        c = unpack_cmd(frame)
        if c is None:
            return f"CMD   {node}  CRC-BAD  {frame.hex()}"
        return (f"CMD   {node}  seq={c.seq:<3} pitch={c.pitch_deg:+8.3f} yaw={c.yaw_deg:+8.3f} deg "
                f"digest={c.digest:#06x}")
    if i == ID_ACT_OUT:
        return f"ACT   -  {frame.hex()}"
    if ID_HEARTBEAT <= i <= ID_HEARTBEAT + 2:
        return f"HB    {NODE_NAMES[i - ID_HEARTBEAT]}  {frame.hex()}"
    if i >= ID_SIM:
        return f"SIM   -  {frame.hex()}"
    return f"??? out-of-schedule id={i:#05x}  {frame.hex()}"
