// SPDX-License-Identifier: MIT
// GENERATED by tools/vehicle/gen_tables.cpp from the 6-DOF vehicle's nominal ascent (sim/vehicle/design.hpp). Do not edit.
// Regenerate: build/host/tfc_gen_tables firmware/app/src/flight_tables.hpp
#pragma once
#include "tfc/controller.hpp"

namespace fc::tables {

inline void load(tfc::GainSchedule& gains, tfc::Guidance& guidance) {
  (void)guidance.add(1U, 0U, 0.0F);
  (void)guidance.add(1U, 666U, 0.0F);
  (void)guidance.add(1U, 1333U, 1.0F);
  (void)guidance.add(1U, 2000U, 1.9371593F);
  (void)guidance.add(1U, 2666U, 3.6858659F);
  (void)guidance.add(1U, 3333U, 5.882858F);
  (void)guidance.add(1U, 4000U, 8.407911F);
  (void)guidance.add(1U, 4666U, 11.147839F);
  (void)guidance.add(1U, 5333U, 14.034486F);
  (void)guidance.add(1U, 6000U, 17.008535F);
  (void)guidance.add(1U, 6666U, 19.983587F);
  (void)guidance.add(1U, 7333U, 22.851122F);
  (void)guidance.add(1U, 8000U, 25.538433F);
  (void)guidance.add(1U, 8666U, 28.024189F);
  (void)guidance.add(1U, 9333U, 30.31013F);
  (void)guidance.add(1U, 10000U, 32.395042F);
  (void)gains.add(0U, tfc::ControllerGains{0.76568544F, 0.4900387F, 0.15313709F});
  (void)gains.add(600U, tfc::ControllerGains{0.74287623F, 0.47348642F, 0.14857525F});
  (void)gains.add(1200U, tfc::ControllerGains{0.7293025F, 0.4577706F, 0.14586051F});
  (void)gains.add(1800U, tfc::ControllerGains{0.72768444F, 0.4429209F, 0.14553688F});
  (void)gains.add(2400U, tfc::ControllerGains{0.74021304F, 0.42900166F, 0.1480426F});
  (void)gains.add(3000U, tfc::ControllerGains{0.76779276F, 0.41611275F, 0.15355855F});
  (void)gains.add(3600U, tfc::ControllerGains{0.8093179F, 0.40438396F, 0.16186358F});
  (void)gains.add(4200U, tfc::ControllerGains{0.86019343F, 0.39396638F, 0.17203869F});
  (void)gains.add(4800U, tfc::ControllerGains{0.9112553F, 0.38502046F, 0.18225107F});
  (void)gains.add(5400U, tfc::ControllerGains{0.9507644F, 0.3776888F, 0.19015288F});
  (void)gains.add(6000U, tfc::ControllerGains{0.9737883F, 0.37203085F, 0.19475767F});
  (void)gains.add(6600U, tfc::ControllerGains{0.9788507F, 0.36796567F, 0.19577014F});
  (void)gains.add(7200U, tfc::ControllerGains{0.9452994F, 0.36543778F, 0.18905987F});
  (void)gains.add(7800U, tfc::ControllerGains{0.8928064F, 0.36414066F, 0.17856129F});
  (void)gains.add(8400U, tfc::ControllerGains{0.82583344F, 0.3635682F, 0.16516669F});
  (void)gains.add(9000U, tfc::ControllerGains{0.75340635F, 0.36311954F, 0.15068127F});
}

}  // namespace fc::tables
